### ISSUE TITLE
Using MacPorts to install Dirty

### ISSUE THREAD

**Issue by radames** [tidalcycles/tidalcycles.github.io#1]
Is interesting to have the instructions using MacPorts? 

It worked fine here doing this:

Considering you have macports installed 

``` bash
sudo port install libsndfile libsamplerate
```

also for jack

``` bash
sudo port install jack
```

then as macports install all libs on `/opt/local/`
I've edited the `Makefile` to point the right direction of `lsndfile` and `lsamplerate`

``` make
CFLAGS += -g -I/opt/local/include -Wall -O3 -std=gnu99
LDFLAGS += -lm -L/opt/local/lib  -llo -lsndfile -lsamplerate
```

then `make`  and works perfectly!

**Comment by lennart** [comment]
I am not so sure whether I would still recommend using macports myself, since Homebrew definitely has taken its place for me. But completeness sake I guess it would be good to have it in the docs.

**Comment by lennart** [comment]
I updated the OS X docs: http://tidal.lurk.org/getting_started.html#tidal-on-mac-os-x

**Comment by radames** [comment]
perfect! I think it will be useful!
