### ISSUE TITLE
add documentation for |+| nudge

### ISSUE THREAD

**Issue by kindohm** [tidalcycles/tidalcycles.github.io#16]

**Comment by lennart** [comment]
if I remember correctly, nudge will delay samples by a certain amount of time to give "human"-like feeling? If so I could add the documentation for it (along with `cut`) right now

**Comment by kindohm** [comment]
yes, although it could result in a very inhuman feeling when large values are used :)

This will introduce "swing": `|+| nudge "[0 0.04]*4"`

**Comment by lennart** [comment]
please check, it's in: http://tidal.lurk.org/functions.html#nudge
