### ISSUE TITLE
add documentation for |+| loop "..." and |+| cut "-1"

### ISSUE THREAD

**Issue by kindohm** [tidalcycles/tidalcycles.github.io#18]

**Comment by lennart** [comment]
is there some kind of combined usage of loop and cut "-1" or is this just a list of things to document separately?

**Comment by kindohm** [comment]
there is combined usage; it originated from this topic: http://lurk.org/groups/tidal/messages/topic/7HtvLi19bM6JDF9qUHg7fY. 

I think `|+| cut "-1"` by itself has no effect. I think `|+| loop "..."` without `|+| cut "-1"` may have some destructive results :fearful:, but I haven't tested this.

**Comment by yaxu** [comment]
`cut "-1"` does have an effect. Here the `off` cuts the `breaks152`

```
d1 $ sound "breaks152*8 off"
  |+| cut "1"
```

here it doesn't:

```
d1 $ sound "breaks152*8 off"
  |+| cut "-1"
```

but you can hear that the breaks152 still cuts itself, as opposed to this:

```
d1 $ sound "breaks152*8 off"
```

Things in a positive group cut each other, those in a negative cut group only cut the same sample name.

**Comment by lennart** [comment]
and I guess cut "-1" makes sense when using `begin "-1"` to allow long samples to play thru have each cycle apply different synth params (without having the original sample play all the way without modifications).

I am currently trying to gather some good examples for both.

For begin "-1" and cut "-1" I guess this one from bgold is good:

``` haskell
cps 0.5
d1 $ sound "breaks125*16" |+| unit "c" |+| cut "-1" |+| begin "-1" |+| coarse
(slow 2 $ "1 2 4 8 16 32 64 128")
```

however for loop I haven't got a good example, as I understand it, it allows you to loop samples directly after they've played, in contrast to just repeating the same sample in the pattern. e.g. an example contrasting both might be good:

compare

``` haskell
d1 $ every 2 (density 2) $ sound "sn*2"
```

with

``` haskell
d1 $ sound "sn" |+| loop (slow 2 $ "2 4")
```

but I guess this is rather contrived. any suggestions for examples?

**Comment by lennart** [comment]
docs for `cut` are there (though not for loop, yet) http://tidal.lurk.org/functions.html#cut

**Comment by yaxu** [comment]
Good stuff, I guess should be under 'synthesiser parameters' tho?

**Comment by lennart** [comment]
oops, yes it should…regenerating

**Comment by lennart** [comment]
`loop` documentation is in since cbc7d274c4ad413a350a019246f885d5ebd3a39a
