### ISSUE TITLE
Update docs for 0.6

### ISSUE THREAD

**Issue by lennart** [tidalcycles/tidalcycles.github.io#19]
Breaking changes from 0.5 to 0.6?

What's new?

**Comment by yaxu** [comment]
I'll have a crack at this now

**Comment by yaxu** [comment]
Had a go at documenting #, |+|, |/| etc..

**Comment by lennart** [comment]
as far as I know 0.6 is fully backwards compatible with 0.5 right?

**Comment by yaxu** [comment]
Yes, apart from bugfixes and `|+|` no longer replacing duplicate parameters but adding them together

**Comment by lennart** [comment]
is there still a way to override duplicate params?

**Comment by yaxu** [comment]
Yes, `|=|`, or `#` for short. I've replaced `|+|` with `#` in the docs.

**Comment by yaxu** [comment]
Some things in here to be documented.. https://github.com/tidalcycles/Tidal/pull/66

**Comment by lennart** [comment]
in general: up to now transitions are not documented at all, right?

**Comment by yaxu** [comment]
That's right

**Comment by yaxu** [comment]
There's a _lot_ of stuff that isn't documented from previous versions.

**Comment by lennart** [comment]
I'd be adding a section for the general part about transitions in "Creating Patterns" and then add all the different transitions in "Reference"

**Comment by lennart** [comment]
I'll be adding a [ticket with a checklist](https://github.com/tidalcycles/tidalcycles.github.io/issues/20)

**Comment by lennart** [comment]
and yes this is a lot ;)

**Comment by lennart** [comment]
I updated the checklist to include _most_ if not all functions from within the source code. I am unsure whether all of them are actively used and should be documented.

**Comment by lennart** [comment]
um, I'll close this now, we still have the checklist, but we are now at 0.8 .. 0.9 and this is old
