### ISSUE TITLE
OS X Installation for brew

### ISSUE THREAD

**Issue by lennart** [tidalcycles/tidalcycles.github.io#24]
it should be noted that:

```
brew install --dry-run haskell-platform
Error: No available formula with the name "haskell-platform"
We no longer package haskell-platform. Consider installing ghc
and cabal-install instead:
  brew install ghc cabal-install

A binary installer is available:
  https://www.haskell.org/platform/mac.html
```

updates for the install docs follow…

**Comment by danhett** [comment]
This is fixed, I just submitted a pull request with a change after testing it. 

"brew install ghc" works fine and also includes cabal so subsequent steps work too. It's also much smaller, haskell-platform has a lot of extra crap in.
