### ISSUE TITLE
tidalcycles.github.io/_patterns/tempo.md typo?

### ISSUE THREAD

**Issue by bhishp** [tidalcycles/tidalcycles.github.io#73]
Hi. New to tidal and reading docs and think there might be a typo in the tempo section.

Setting BPM section says:

```
-- sets a tempo of 170 BPM:
bps (120/60)
```

Should this actually say sets a tempo of 120BPM?

**Comment by pd3v** [comment]
Already changed.

**Comment by yaxu** [comment]
yes I think I fixed + forgot to close the issue
