### ISSUE TITLE
Control surface: code evaluation

### ISSUE THREAD

**Issue by dandrewstewart** [tidalcycles/tidalcycles.github.io#99]
I'd like to send an OSC message from, say, a gestural controller and that message evaluates all the code. Could the MIDI features be extended to include "code evaluation/execution"?  This issue could be related to an early github issue "Batch evaluate/execute #98".

**Comment by kindohm** [comment]
@dandrewstewart your issue is probably better suited for the Tidal project: https://github.com/tidalcycles/tidal. This repo is the source code for an earlier version of the tidalcycles.org web site that is no longer used (just submitted #100).

**Comment by dandrewstewart** [comment]
Thank you. Not always easy to follow where the coffee machine (room) is.
